# Generated by Django 4.2.6 on 2023-10-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='1996-03-08'),
            preserve_default=False,
        ),
    ]
